
//-------------------------------- Transit lead time --> START ---------------------------------------
export const rawTransitData = [
  { docRcd: "23-08-21", arrivalDt: "08-10-21", leadTime: 46 },
  { docRcd: "31-08-21", arrivalDt: "04-10-21", leadTime: 34 },
  { docRcd: "06-09-21", arrivalDt: "30-09-21", leadTime: 24 },
  { docRcd: "06-09-21", arrivalDt: "06-10-21", leadTime: 30 },
  { docRcd: "06-09-21", arrivalDt: "07-10-21", leadTime: 31 },
  { docRcd: "06-09-21", arrivalDt: "08-10-21", leadTime: 32 },
  { docRcd: "15-09-21", arrivalDt: "08-10-21", leadTime: 23 },
  { docRcd: "23-09-21", arrivalDt: "13-10-21", leadTime: 20 },
  { docRcd: "29-09-21", arrivalDt: "11-10-21", leadTime: 12 },
  { docRcd: "04-10-21", arrivalDt: "01-11-21", leadTime: 28 },
  { docRcd: "13-10-21", arrivalDt: "01-11-21", leadTime: 19 },
  { docRcd: "13-10-21", arrivalDt: "03-11-21", leadTime: 21 },
  { docRcd: "13-10-21", arrivalDt: "10-11-21", leadTime: 28 },
  { docRcd: "23-10-21", arrivalDt: "08-11-21", leadTime: 16 },
  { docRcd: "23-10-21", arrivalDt: "10-11-21", leadTime: 18 },
  { docRcd: "23-10-21", arrivalDt: "11-11-21", leadTime: 19 },
  { docRcd: "23-10-21", arrivalDt: "12-11-21", leadTime: 20 },
  { docRcd: "23-10-21", arrivalDt: "25-11-21", leadTime: 33 },
  { docRcd: "25-10-21", arrivalDt: "16-11-21", leadTime: 22 },
  { docRcd: "27-10-21", arrivalDt: "21-11-21", leadTime: 25 },
  { docRcd: "03-11-21", arrivalDt: "04-12-21", leadTime: 31 },
  { docRcd: "12-11-21", arrivalDt: "23-11-21", leadTime: 11 },
  { docRcd: "12-11-21", arrivalDt: "01-12-21", leadTime: 19 },
  { docRcd: "16-11-21", arrivalDt: "29-11-21", leadTime: 13 },
  { docRcd: "16-11-21", arrivalDt: "01-12-21", leadTime: 15 },
  { docRcd: "16-11-21", arrivalDt: "06-12-21", leadTime: 20 },
  { docRcd: "16-11-21", arrivalDt: "13-12-21", leadTime: 27 },
  { docRcd: "16-11-21", arrivalDt: "24-12-21", leadTime: 38 },
  { docRcd: "16-11-21", arrivalDt: "28-12-21", leadTime: 42 },
  { docRcd: "17-11-21", arrivalDt: "21-11-21", leadTime: 4 },
  { docRcd: "22-11-21", arrivalDt: "04-12-21", leadTime: 12 },
  { docRcd: "22-11-21", arrivalDt: "29-12-21", leadTime: 37 },
  { docRcd: "24-11-21", arrivalDt: "13-12-21", leadTime: 19 },
  { docRcd: "29-11-21", arrivalDt: "14-12-21", leadTime: 15 },
  { docRcd: "29-11-21", arrivalDt: "28-12-21", leadTime: 29 },
  { docRcd: "01-12-21", arrivalDt: "21-12-21", leadTime: 20 },
  { docRcd: "07-12-21", arrivalDt: "05-01-22", leadTime: 29 },
  { docRcd: "07-12-21", arrivalDt: "06-01-22", leadTime: 30 },
  { docRcd: "08-12-21", arrivalDt: "12-12-21", leadTime: 4 },
  { docRcd: "15-12-21", arrivalDt: "04-01-22", leadTime: 20 },
  { docRcd: "22-12-21", arrivalDt: "05-01-22", leadTime: 14 },
  { docRcd: "22-12-21", arrivalDt: "07-01-22", leadTime: 16 },
  { docRcd: "22-12-21", arrivalDt: "13-01-22", leadTime: 22 },
  { docRcd: "28-12-21", arrivalDt: "04-01-22", leadTime: 7 },
  { docRcd: "28-12-21", arrivalDt: "06-01-22", leadTime: 9 },
];
//-------------------------------- Transit lead time --> END ---------------------------------------

//-------------------------------- Clearance lead time --> START ---------------------------------------
export const clearanceLeadTimeData = [
  { OOC_date: "06-03-23", ETA: "02-03-23", clearance_lead_time: 4 },
  { OOC_date: "04-03-23", ETA: "02-03-23", clearance_lead_time: 2 },
  { OOC_date: "30-03-23", ETA: "24-03-23", clearance_lead_time: 6 },
  { OOC_date: "23-03-23", ETA: "20-03-23", clearance_lead_time: 3 },
  { OOC_date: "19-03-23", ETA: "18-03-23", clearance_lead_time: 1 },
  { OOC_date: "26-03-23", ETA: "26-03-23", clearance_lead_time: 0 },
  { OOC_date: "19-04-23", ETA: "13-04-23", clearance_lead_time: 6 },
  { OOC_date: "25-04-23", ETA: "01-05-23", clearance_lead_time: -6 },
  { OOC_date: "05-05-23", ETA: "02-05-23", clearance_lead_time: 3 },
  { OOC_date: "12-05-23", ETA: "08-05-23", clearance_lead_time: 4 },
  { OOC_date: "16-05-23", ETA: "09-05-23", clearance_lead_time: 7 },
  { OOC_date: "18-05-23", ETA: "09-05-23", clearance_lead_time: 9 },
  { OOC_date: "18-05-23", ETA: "13-05-23", clearance_lead_time: 5.1 },
  { OOC_date: "07-06-23", ETA: "07-06-23", clearance_lead_time: 0 },
  { OOC_date: "04-07-23", ETA: "29-06-23", clearance_lead_time: 5 },
  { OOC_date: "24-06-23", ETA: "15-06-23", clearance_lead_time: 9 },
  { OOC_date: "04-07-23", ETA: "28-06-23", clearance_lead_time: 6 },
  { OOC_date: "26-06-23", ETA: "22-06-23", clearance_lead_time: 4 },
  { OOC_date: "01-08-23", ETA: "26-07-23", clearance_lead_time: 6 },
  { OOC_date: "27-07-23", ETA: "26-07-23", clearance_lead_time: 1 },
  { OOC_date: "03-08-23", ETA: "15-07-23", clearance_lead_time: 19 },
  { OOC_date: "08-08-23", ETA: "30-07-23", clearance_lead_time: 9 },
  { OOC_date: "27-07-23", ETA: "26-07-23", clearance_lead_time: 1 },
  { OOC_date: "24-07-23", ETA: "23-07-23", clearance_lead_time: 1 },
  { OOC_date: "21-07-23", ETA: "19-07-23", clearance_lead_time: 2 },
  { OOC_date: "26-07-23", ETA: "17-07-23", clearance_lead_time: 5 },
  { OOC_date: "13-08-23", ETA: "11-08-23", clearance_lead_time: 5.4 },
  { OOC_date: "17-08-23", ETA: "11-08-23", clearance_lead_time: 6 },
  { OOC_date: "31-08-23", ETA: "30-08-23", clearance_lead_time: 19 },
  { OOC_date: "31-08-23", ETA: "30-08-23", clearance_lead_time: 11 },
  { OOC_date: "12-09-23", ETA: "12-09-23", clearance_lead_time: 3 },
  { OOC_date: "14-09-23", ETA: "12-09-23", clearance_lead_time: 3 },
  { OOC_date: "20-09-23", ETA: "17-09-23", clearance_lead_time: 1 },
  { OOC_date: "23-09-23", ETA: "21-09-23", clearance_lead_time: 3 },
  { OOC_date: "06-11-23", ETA: "03-11-23", clearance_lead_time: 3 },
  { OOC_date: "04-11-23", ETA: "03-11-23", clearance_lead_time: 5.6 },
  { OOC_date: "30-11-23", ETA: "25-11-23", clearance_lead_time: 16 },
  { OOC_date: "19-12-23", ETA: "18-12-23", clearance_lead_time: 5 },
  { OOC_date: "27-12-23", ETA: "27-12-23", clearance_lead_time: 7 },
  { OOC_date: "26-12-23", ETA: "23-12-23", clearance_lead_time: 10 },
  { OOC_date: "01-01-24", ETA: "28-12-23", clearance_lead_time: 10 },
  { OOC_date: "04-01-24", ETA: "02-01-23", clearance_lead_time: 8 },
  { OOC_date: "10-01-24", ETA: "10-01-23", clearance_lead_time: 13 },
  { OOC_date: "29-01-24", ETA: "28-01-24", clearance_lead_time: 11 },
  { OOC_date: "22-05-24", ETA: "21-05-24", clearance_lead_time: 3 },
  { OOC_date: "24-05-24", ETA: "16-05-24", clearance_lead_time: 5.9 },
  { OOC_date: "05-06-24", ETA: "04-06-24", clearance_lead_time: 3 },
  { OOC_date: "15-06-24", ETA: "12-06-24", clearance_lead_time: 1 },
  { OOC_date: "14-06-24", ETA: "12-06-24", clearance_lead_time: 1 },
  { OOC_date: "15-06-24", ETA: "12-06-24", clearance_lead_time: 4 },
  { OOC_date: "22-06-24", ETA: "18-06-24", clearance_lead_time: 1 }
];
//-------------------------------- Clearance lead time --> END ---------------------------------------

//-------------------------------- Supplier Data --> START ---------------------------------------
export const supplierData = [
  { "SUPPLIER NAME": "JIANGXI KELAM", "Gross weight in Tons": 27.2 },
  { "SUPPLIER NAME": "ARSHINE", "Gross weight in Tons": 109.9 },
  { "SUPPLIER NAME": "ARSHINE LIFESCIENCE", "Gross weight in Tons": 55.6 },
  { "SUPPLIER NAME": "ARSHINE LIFESICENE", "Gross weight in Tons": 54.6 },
  { "SUPPLIER NAME": "BEYRON LTD", "Gross weight in Tons": 27.2 },
  { "SUPPLIER NAME": "CJ BIO MALAYSIN", "Gross weight in Tons": 19.4 },
  { "SUPPLIER NAME": "CJ CHEILJEDANG", "Gross weight in Tons": 17.7 },
  { "SUPPLIER NAME": "DAESANG CORPORATION", "Gross weight in Tons": 254.6 },
  { "SUPPLIER NAME": "ECO NUTRITION", "Gross weight in Tons": 82.186 },
  { "SUPPLIER NAME": "ECO NUTRITION", "Gross weight in Tons": 81.5 },
  { "SUPPLIER NAME": "EOC NUTRITION", "Gross weight in Tons": 55.6 },
  { "SUPPLIER NAME": "GOLDEN GAIN", "Gross weight in Tons": 111.2 },
  { "SUPPLIER NAME": "GOLDEN GAIN GROUP HK LTD", "Gross weight in Tons": 361.8 },
  { "SUPPLIER NAME": "JIANGXI KELEM", "Gross weight in Tons": 27.216 },
  { "SUPPLIER NAME": "SHANDONG GOLDEN", "Gross weight in Tons": 27.2 },
  { "SUPPLIER NAME": "SHANGHAI NUVIT", "Gross weight in Tons": 55.6 },
  { "SUPPLIER NAME": "Grand Total", "Gross weight in Tons": 1368.5 },
];
//-------------------------------- Supplier Data --> END ---------------------------------------

//-------------------------------- Material Data --> START ---------------------------------------
export const materialData = [
  { Description: "L LYSINE MONOHYDROCHOLORIDE 98.5%", "Sum of Gross weight in Tons": 1106.09 },
  { Description: "L LYSINE MONOHYDROCHOLORIDE 99%", "Sum of Gross weight in Tons": 24.3 },
  { Description: "L LYSINE SULPHATE", "Sum of Gross weight in Tons": 164.99 },
  { Description: "L METHONINE", "Sum of Gross weight in Tons": 19.38 },
  { Description: "L THREONINE", "Sum of Gross weight in Tons": 81.52 },
  { Description: "Grand Total", "Sum of Gross weight in Tons": 1396.28 },
];
//-------------------------------- Material Data --> END ---------------------------------------

//-------------------------------- Shipments handled Data --> START ---------------------------------------
export const shipmentData = [
  { STATUS: "PENDING", "GR. WT.": 13788, SHIPPER: "Zapp Precision Metals (Sweden) AB" },
  { STATUS: "PENDING", "GR. WT.": 13933, SHIPPER: "Zapp Precision Metals (Sweden) AB" },
  { STATUS: "PENDING", "GR. WT.": 4612, SHIPPER: "KS GLEITLAGER GMBH" },
  { STATUS: "PENDING", "GR. WT.": 391, SHIPPER: "MERITOR HEAVY BRAKING SYSTEMS (UK) LIMITED" },
  { STATUS: "PENDING", "GR. WT.": 74052.5, SHIPPER: "PRESS METAL BINTULU SDN BHD" },
  { STATUS: "CLEARANCE", "GR. WT.": 2472, SHIPPER: "BAUMANN" },
  { STATUS: "CLEARANCE", "GR. WT.": 14715, SHIPPER: "ZAPP PRECISION" },
  { STATUS: "CLEARANCE", "GR. WT.": 790.7, SHIPPER: "SAINT GOBAIN" },
  { STATUS: "CLEARANCE", "GR. WT.": 13092, SHIPPER: "TMD FRICTIONS" },
  { STATUS: "CLEARANCE", "GR. WT.": 1455, SHIPPER: "VALSFAN" },
  { STATUS: "CLEARANCE", "GR. WT.": 2770, SHIPPER: "FEDERAL MOGUL" },
  { STATUS: "CLEARANCE", "GR. WT.": 171.39, SHIPPER: "HONSEL" },
  { STATUS: "CLEARANCE", "GR. WT.": 22614, SHIPPER: "EURAL GNUTTI" },
  { STATUS: "CLEARANCE", "GR. WT.": 50307, SHIPPER: "HYDRO ALUMINIUM" },
  { STATUS: "CLEARANCE", "GR. WT.": 260, SHIPPER: "CIMAP" },
  { STATUS: "CLEARANCE", "GR. WT.": 1822, SHIPPER: "KS GLEITLAGER" },
  { STATUS: "CLEARANCE", "GR. WT.": 315, SHIPPER: "SHIJIAZHUANG" },
  { STATUS: "CLEARANCE", "GR. WT.": 6433, SHIPPER: "FEDERAL MOGUL" },
  { STATUS: "CLEARANCE", "GR. WT.": 13429, SHIPPER: "TMD FRICTION" },
  { STATUS: "CLEARANCE", "GR. WT.": 840, SHIPPER: "THE HARBORO" },
  { STATUS: "CLEARANCE", "GR. WT.": 840, SHIPPER: "THE HARBORO" },
  { STATUS: "CLEARANCE", "GR. WT.": 51300, SHIPPER: "HYDRO ALUMINIUM" },
  { STATUS: "CLEARANCE", "GR. WT.": 600, SHIPPER: "VALSFAN" },
  { STATUS: "CLEARANCE", "GR. WT.": 2476, SHIPPER: "BAUMANN" },
  { STATUS: "CLEARANCE", "GR. WT.": 1615, SHIPPER: "WESTLEY" },
  { STATUS: "CLEARANCE", "GR. WT.": 840, SHIPPER: "THE HARBORO" },
  { STATUS: "CLEARANCE", "GR. WT.": 76838, SHIPPER: "HYDRO ALUMINIUM" },
  { STATUS: "CLEARANCE", "GR. WT.": 6444, SHIPPER: "FEDERAL MOGUL" },
  { STATUS: "CLEARANCE", "GR. WT.": 1260, SHIPPER: "THE HARBORO" },
  { STATUS: "CLEARANCE", "GR. WT.": 791, SHIPPER: "SAINT GOBAIN" },
  { STATUS: "CLEARANCE", "GR. WT.": 6465, SHIPPER: "FEDERAL MOGUL" },
  { STATUS: "CLEARANCE", "GR. WT.": 970, SHIPPER: "VALSFAN" },
  { STATUS: "CLEARANCE", "GR. WT.": 25246, SHIPPER: "EURAL GNUTTI" },
  { STATUS: "CLEARANCE", "GR. WT.": 51804, SHIPPER: "HYDRO ALUMINIUM" },
  { STATUS: "CLEARANCE", "GR. WT.": 260, SHIPPER: "CIMAP" },
  { STATUS: "CLEARANCE", "GR. WT.": 3802, SHIPPER: "MERITOR HVBS" },
  { STATUS: "CLEARANCE", "GR. WT.": 1135, SHIPPER: "WESTLEY" },
  { STATUS: "CLEARANCE", "GR. WT.": 840, SHIPPER: "THE HARBORO" },
  { STATUS: "CLEARANCE", "GR. WT.": 1050, SHIPPER: "THE HARBORO" },
  { STATUS: "CLEARANCE", "GR. WT.": 11237, SHIPPER: "KS GLEITLAGER" },
  { STATUS: "CLEARANCE", "GR. WT.": 1088.81, SHIPPER: "HONSEL" },
  { STATUS: "CLEARANCE", "GR. WT.": 6452, SHIPPER: "FEDERAL MOGUL" },
  { STATUS: "CLEARANCE", "GR. WT.": 1297, SHIPPER: "FREUDENBERG" },
  { STATUS: "CLEARANCE", "GR. WT.": 1200, SHIPPER: "THE HARBORO" },
  { STATUS: "CLEARANCE", "GR. WT.": 49988, SHIPPER: "HYDRO ALUMINIUM" },
  { STATUS: "CLEARANCE", "GR. WT.": 970, SHIPPER: "VALSFAN" },
  { STATUS: "CLEARANCE", "GR. WT.": 51003, SHIPPER: "HYDRO ALUMINIUM" },
  { STATUS: "CLEARANCE", "GR. WT.": 1971.2, SHIPPER: "BAUMANN" },
  { STATUS: "CLEARANCE", "GR. WT.": 16100, SHIPPER: "ZAPP PRECISION" },
  { STATUS: "CLEARANCE", "GR. WT.": 342.78, SHIPPER: "HONSEL" },
  { STATUS: "CLEARANCE", "GR. WT.": 1186, SHIPPER: "FREUDENBERG" },
  { STATUS: "CLEARANCE", "GR. WT.": 12922, SHIPPER: "FEDERAL MOGUL" },
  { STATUS: "CLEARANCE", "GR. WT.": 12684, SHIPPER: "TMD FRICTION" },
  { STATUS: "CLEARANCE", "GR. WT.": 1061, SHIPPER: "KS GLEITLAGER" },
  { STATUS: "CLEARANCE", "GR. WT.": 600, SHIPPER: "KS GLEITLAGER" },
  { STATUS: "CLEARANCE", "GR. WT.": 50476, SHIPPER: "HYDRO ALUMINIUM" },
  { STATUS: "CLEARANCE", "GR. WT.": 791, SHIPPER: "SAINT GOBAIN" },
  { STATUS: "CLEARANCE", "GR. WT.": 6441, SHIPPER: "FEDERAL MOGUL" },
  { STATUS: "CLEARANCE", "GR. WT.": 98832, SHIPPER: "PRESS METAL" },
  { STATUS: "CLEARANCE", "GR. WT.": 260, SHIPPER: "CIMAP" },
  { STATUS: "CLEARANCE", "GR. WT.": 1740, SHIPPER: "THE HARBORO" },
  { STATUS: "CLEARANCE", "GR. WT.": 765, SHIPPER: "VALSFAN" },
  { STATUS: "CLEARANCE", "GR. WT.": 1971, SHIPPER: "BAUMANN" },
  { STATUS: "CLEARANCE", "GR. WT.": 1260, SHIPPER: "THE HARBORO" },
  { STATUS: "CLEARANCE", "GR. WT.": 3684, SHIPPER: "MERITOR HVBS" },
  { STATUS: "CLEARANCE", "GR. WT.": 2690, SHIPPER: "IMV EUROPE" },
  { STATUS: "CLEARANCE", "GR. WT.": 49608, SHIPPER: "HYDRO ALUMINIUM" },
  { STATUS: "CLEARANCE", "GR. WT.": 51116, SHIPPER: "HYDRO ALUMINIUM" }
];
//-------------------------------- Shipments handled Data --> END ---------------------------------------

//-------------------------------- Shipment Costs Analysis by Shipper --> START ---------------------------------------
export const shipmentCostsData = [
  { "GR. WT.": 2472, "SHIPPER": "BAUMANN", "STORAGE / DEMURRAGE": "USD 80", "detention charges": "USD 59" },
  { "GR. WT.": 14715, "SHIPPER": "ZAPP PRECISION", "STORAGE / DEMURRAGE": "USD 81", "detention charges": "USD 59" },
  { "GR. WT.": 790.7, "SHIPPER": "SAINT GOBAIN", "STORAGE / DEMURRAGE": "USD 82", "detention charges": "USD 59" },
  { "GR. WT.": 13092, "SHIPPER": "TMD FRICTIONS", "STORAGE / DEMURRAGE": "USD 83", "detention charges": "USD 59" },
  { "GR. WT.": 1455, "SHIPPER": "VALSFAN", "STORAGE / DEMURRAGE": "USD 84", "detention charges": "USD 59" },
  { "GR. WT.": 2770, "SHIPPER": "FEDERAL MOGUL", "STORAGE / DEMURRAGE": "USD 85", "detention charges": "USD 59" },
  { "GR. WT.": 171.39, "SHIPPER": "HONSEL", "STORAGE / DEMURRAGE": "USD 86", "detention charges": "USD 59" },
  { "GR. WT.": 22614, "SHIPPER": "EURAL GNUTTI", "STORAGE / DEMURRAGE": "USD 87", "detention charges": "USD 59" },
  { "GR. WT.": 50307, "SHIPPER": "HYDRO ALUMINIUM", "STORAGE / DEMURRAGE": "USD 88", "detention charges": "USD 59" },
  { "GR. WT.": 260, "SHIPPER": "CIMAP", "STORAGE / DEMURRAGE": "USD 89", "detention charges": "USD 59" },
  { "GR. WT.": 1822, "SHIPPER": "KS GLEITLAGER", "STORAGE / DEMURRAGE": "USD 90", "detention charges": "USD 59" },
  { "GR. WT.": 315, "SHIPPER": "SHIJIAZHUANG", "STORAGE / DEMURRAGE": "USD 91", "detention charges": "USD 59" },
  { "GR. WT.": 6433, "SHIPPER": "FEDERAL MOGUL", "STORAGE / DEMURRAGE": "USD 92", "detention charges": "USD 59" },
  { "GR. WT.": 13429, "SHIPPER": "TMD FRICTION", "STORAGE / DEMURRAGE": "USD 93", "detention charges": "USD 59" },
  { "GR. WT.": 840, "SHIPPER": "THE HARBORO", "STORAGE / DEMURRAGE": "USD 94", "detention charges": "USD 59" },
  { "GR. WT.": 840, "SHIPPER": "THE HARBORO", "STORAGE / DEMURRAGE": "USD 95", "detention charges": "USD 59" },
  { "GR. WT.": 51300, "SHIPPER": "HYDRO ALUMINIUM", "STORAGE / DEMURRAGE": "USD 96", "detention charges": "USD 59" },
  { "GR. WT.": 600, "SHIPPER": "VALSFAN", "STORAGE / DEMURRAGE": "USD 97", "detention charges": "USD 59" },
  { "GR. WT.": 2476, "SHIPPER": "BAUMANN", "STORAGE / DEMURRAGE": "USD 98", "detention charges": "USD 59" },
  { "GR. WT.": 1615, "SHIPPER": "WESTLEY", "STORAGE / DEMURRAGE": "USD 99", "detention charges": "USD 59" },
  { "GR. WT.": 840, "SHIPPER": "THE HARBORO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 76838, "SHIPPER": "HYDRO ALUMINIUM", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 6444, "SHIPPER": "FEDERAL MOGUL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1260, "SHIPPER": "THE HARBORO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 791, "SHIPPER": "SAINT GOBAIN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 6465, "SHIPPER": "FEDERAL MOGUL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 970, "SHIPPER": "VALSFAN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 25246, "SHIPPER": "EURAL GNUTTI", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 51804, "SHIPPER": "HYDRO ALUMINIUM", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 260, "SHIPPER": "CIMAP", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 3802, "SHIPPER": "MERITOR HVBS", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1135, "SHIPPER": "WESTLEY", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 840, "SHIPPER": "THE HARBORO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1050, "SHIPPER": "THE HARBORO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 11237, "SHIPPER": "KS GLEITLAGER", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1088.81, "SHIPPER": "HONSEL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 6452, "SHIPPER": "FEDERAL MOGUL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1297, "SHIPPER": "FREUDENBERG", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1200, "SHIPPER": "THE HARBORO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 49988, "SHIPPER": "HYDRO ALUMINIUM", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 970, "SHIPPER": "VALSFAN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 51003, "SHIPPER": "HYDRO ALUMINIUM", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1971.2, "SHIPPER": "BAUMANN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 16100, "SHIPPER": "ZAPP PRECISION", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 342.78, "SHIPPER": "HONSEL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1186, "SHIPPER": "FREUDENBERG", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 12922, "SHIPPER": "FEDERAL MOGUL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 12684, "SHIPPER": "TMD FRICTION", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1061, "SHIPPER": "KS GLEITLAGER", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 600, "SHIPPER": "KS GLEITLAGER", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 50476, "SHIPPER": "HYDRO ALUMINIUM", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 791, "SHIPPER": "SAINT GOBAIN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 6441, "SHIPPER": "FEDERAL MOGUL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 98832, "SHIPPER": "PRESS METAL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 260, "SHIPPER": "CIMAP", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1740, "SHIPPER": "THE HARBORO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 765, "SHIPPER": "VALSFAN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1971, "SHIPPER": "BAUMANN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1260, "SHIPPER": "THE HARBORO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 3684, "SHIPPER": "MERITOR HVBS", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 2690, "SHIPPER": "IMV EUROPE", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 49608, "SHIPPER": "HYDRO ALUMINIUM", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 51116, "SHIPPER": "HYDRO ALUMINIUM", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1194, "SHIPPER": "KS GLEITLAGER", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 2905.91, "SHIPPER": "HONSEL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 503, "SHIPPER": "CIMAP", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1470, "SHIPPER": "WESTLEY", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 791, "SHIPPER": "SAINT GOBAIN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 10666, "SHIPPER": "TMD FRICTION", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 26840, "SHIPPER": "BAHRAIN ALLOYS", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1140, "SHIPPER": "THE HARBORO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1215, "SHIPPER": "FREUDENBERG", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 50046, "SHIPPER": "HYDRO ALUMINIUM", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 485, "SHIPPER": "VALSFAN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 485, "SHIPPER": "VALSFAN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 3482, "SHIPPER": "MERITOR HVBS", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 50656, "SHIPPER": "HYDRO ALUMINIUM", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 21786, "SHIPPER": "EURAL GNUTTI", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 14264, "SHIPPER": "FEDERAL MOGUL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 14912, "SHIPPER": "TMD FRICTION", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1919, "SHIPPER": "KS GLEITLAGER", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 800, "SHIPPER": "THE HARBORO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1211, "SHIPPER": "FREUDENBERG", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 3275, "SHIPPER": "FEDERAL MOGUL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 945, "SHIPPER": "SHIJIAZHUANG", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1959, "SHIPPER": "BAUMANN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1292, "SHIPPER": "WESTLEY", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 840, "SHIPPER": "THE HARBORO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1292, "SHIPPER": "WESTLEY", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 50978, "SHIPPER": "HYDRO ALIMINIUM", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 25526, "SHIPPER": "BAHRAIN ALLOYS", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 480, "SHIPPER": "VALSFAN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 3535, "SHIPPER": "MERITOR HVBS", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 51319, "SHIPPER": "HYDRO ALIMINIUM", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 51502, "SHIPPER": "HYDRO ALIMINIUM", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 49308, "SHIPPER": "PRESS METAL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 503, "SHIPPER": "CIMAP", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 675.83, "SHIPPER": "HONSEL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 973, "SHIPPER": "SAINT GOBAIN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 2788, "SHIPPER": "KS GLEITLAGER", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 2765, "SHIPPER": "FEDERAL MOGUL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 630, "SHIPPER": "SHIJIAZHUANG", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1400, "SHIPPER": "THE HARBORO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 800, "SHIPPER": "THE HARBORO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1147, "SHIPPER": "FREUDENBERG", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 3216, "SHIPPER": "KS GLEITLAGER", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 965, "SHIPPER": "VALSFAN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 480, "SHIPPER": "VALSFAN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1908, "SHIPPER": "BAUMANN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1036, "SHIPPER": "SAINT GOBAIN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 785, "SHIPPER": "HAIDA", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 260, "SHIPPER": "CIMAP", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 49517, "SHIPPER": "HYDRO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 50193, "SHIPPER": "HYDRO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 15897, "SHIPPER": "ZAPP PRECISION", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 49331, "SHIPPER": "PRESS METAL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 480, "SHIPPER": "VALSFAN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 2769, "SHIPPER": "FEDERAL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 3434, "SHIPPER": "KS GLEITLAGER", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1035, "SHIPPER": "FREUDENBERG", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 2480, "SHIPPER": "THE HARBORO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 23817, "SHIPPER": "EURAL GNUTTI", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 5890, "SHIPPER": "TMD FRICTIONS", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 6378, "SHIPPER": "FEDERAL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 7138, "SHIPPER": "FEDERAL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 580.36, "SHIPPER": "HONSEL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 2160, "SHIPPER": "THE HARBORO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 24955, "SHIPPER": "BAHRAIN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 49051, "SHIPPER": "PRESS METAL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 480, "SHIPPER": "VALSFAN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 2808, "SHIPPER": "MERITOR", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1292, "SHIPPER": "WESTLEY", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1023.3, "SHIPPER": "SAINT GOBAIN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1292, "SHIPPER": "WESTLEY", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1946, "SHIPPER": "BAUMANN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 2766, "SHIPPER": "FEDERAL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 2244, "SHIPPER": "KS GLEITLAGER", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 620.35, "SHIPPER": "TMD FRICTIONS", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 274.59, "SHIPPER": "HONSEL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 800, "SHIPPER": "THE HARBORO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 800, "SHIPPER": "THE HARBORO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 10820, "SHIPPER": "ZAPP PRECISION", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 480, "SHIPPER": "VALSFAN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 6409, "SHIPPER": "FEDERAL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 49418, "SHIPPER": "PRESS METAL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 3728, "SHIPPER": "KS GLEITLAGER", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 13227, "SHIPPER": "TMD FRICTION", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 2764, "SHIPPER": "FEDERAL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1023, "SHIPPER": "FREUDENBERG", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 315, "SHIPPER": "SHIJIANG TMD", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1230, "SHIPPER": "ZHEJIANG WBK", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 4997, "SHIPPER": "ZAPP PRECISION", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1946, "SHIPPER": "BAUMANN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 480, "SHIPPER": "VALSFAN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 50405, "SHIPPER": "HYDRO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 315, "SHIPPER": "SHIJIANG TMD", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 50168, "SHIPPER": "HYDRO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 7929, "SHIPPER": "ZAPP PRECISION", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 800, "SHIPPER": "THE HARBORO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 800, "SHIPPER": "THE HARBORO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1110.5, "SHIPPER": "WESTLEY", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 2869, "SHIPPER": "KS GLEITLAGER", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 526.3, "SHIPPER": "SAINTGOBAIN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 6402, "SHIPPER": "FEDERAL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 3716, "SHIPPER": "MAT COMMERCIAL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 3238, "SHIPPER": "KS GLEITLAGER", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1217.2, "SHIPPER": "FREUDENBERG", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 2770, "SHIPPER": "FEDERAL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 8758, "SHIPPER": "TMD FRICTION", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 800, "SHIPPER": "THE HARBORO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 503, "SHIPPER": "CIMAP", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1943.1, "SHIPPER": "BAUMANN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 480, "SHIPPER": "VALSFAN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 49150, "SHIPPER": "HYDRO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 49309, "SHIPPER": "HYDRO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 22005, "SHIPPER": "EURAL GNUTTI", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 830.4, "SHIPPER": "WESTLEY", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 50624, "SHIPPER": "HYDRO ALUMINIUM", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 315, "SHIPPER": "SHIJIAZHUANG TMD", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 2770, "SHIPPER": "FEDERAL MOGUL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 3042, "SHIPPER": "KS GLEITLAGER", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 600, "SHIPPER": "THE HARBORO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 480, "SHIPPER": "VALSFAN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 4461, "SHIPPER": "MERITOR HVBS", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 1233.6, "SHIPPER": "FREUDENBERG", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 2763, "SHIPPER": "FEDERAL MOGUL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 136, "SHIPPER": "BAUMANN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 3582, "SHIPPER": "KS GLEITLAGER", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 50111, "SHIPPER": "QATAR", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 2990, "SHIPPER": "KS GLEITLAGER", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 2758, "SHIPPER": "FEDERAL MOGUL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 825.86, "SHIPPER": "HONSEL", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 800, "SHIPPER": "THE HARBORO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 800, "SHIPPER": "THE HARBORO", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 480, "SHIPPER": "VALSFAN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 503, "SHIPPER": "CIMAP", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 49929, "SHIPPER": "HYDRO ALUMNIUM", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 10929, "SHIPPER": "ZAPP PRECISION", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 2087, "SHIPPER": "BAUMANN", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
  { "GR. WT.": 49846, "SHIPPER": "HYDRO ALUMNIUM", "STORAGE / DEMURRAGE": "USD 100", "detention charges": "USD 59" },
];
//-------------------------------- Shipment Costs Analysis by Shipper --> END ---------------------------------------

// Data for Donut (Origin Type Breakdown)
// export const originData = [
//   { label: "DALIAN /CHINA", value: 811 },
//   { label: "KWANGYANG/KOREA", value: 145 },
//   { label: "PORTKELANG/MALAYSIA", value: 19 },
//   { label: "QINGDAO/CHINA", value: 45 },
//   { label: "SHANGHAI/CHINA", value: 27 },
//   { label: "SURABAYA /INDONESIA", value: 18 },
//   { label: "TIANJIN/CHINA", value: 193 },
//   { label: "XINGANG/CHINA", value: 138 },
//   { label: "Grand Total", value: 1396 },
// ];

// Data for Donut (Shipment Processing Method Type Breakdown)
// export const processingMethodData = [
//   { label: "ALL CARGO", value: 2 },
//   { label: "CONTINENTAL CFS", value: 1 },
//   { label: "DPD", value: 13 },
//   { label: "SANCO CFS", value: 36 },
//   { label: "Grand Total", value: 52 },
// ];